language: ruby
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
<<<<<<< Updated upstream
    secure: "KEl0F/EFLLVMC708oFCc7RjKojE3g27+XjiGE0auarm8ATMLL5p8pK3W540tpYobOKofwS5Vy9edlLHc56ZfHWErZ0+NW+G07/OB6DVwytBwR98lbFLbcV+QbcQ6WhybAsDQ7CBsQ7X6y9dE0hVDPIJ3kIhBPCpSFzwTie2g3LPlNAho9Buh/BCJ1BZbEGIuIHLGSeyV8LUPgGl60d5Ns6hMoNY+4T35J/ceHhgQwLAyna1P5dxmMbrRhfeY1aJthGoZxjXvVY0J1WOIt/+HF9s1Qk9FchL2lstUJ3RChVK1UimzQ9XaXm3Zpjtk2QRJ86HNmSdVw3UauiLZUUYbhjvunxgiHrFleTA/owbaNH5UdUOcwQoAnzmI6frC9Zvg/jhkzCns2HGn2PdadfokHZwnKzb+DijWjW7Pr5XbRwzbK/s6XufwJibrrvNpaeQJRgKMSYyrhtmdzqzIeNMMZz95qDAcL2SzodoBGO5eEBgmzswnnsxOt5p/K/1X4InM0JeWviCwkDWAEtDhRdKWSpaR81qDXWaoenxIMLbf/EEyZpUsWVXYGp77eO9uE2ANvAPkf0ctm/dGcL/dRCBP/WpoBrGO41D5Vdyli/q65Bw3ar7mbPkKhzJRUFyN9r7A7AnqrT98K1P5X+O03IXT6y3ugTmG8dGJNU3DLP/VFvY="
  app: zjedliwe-pl
=======
  app: ncc-zjadliwe
    secure: "vY39H4JozVA9TWVSU+/owXS5gX7eMoi9Rp1pFeUIN5Uj9gcYi5QDNTDvdyq9agc96IC09psD6nw7bB4pqrYNt5Zl2wnOPCxKeb2Qsbj4wtPtswTXaJSIAK+7qeyzVkuJETWZa4cQF2WRT7g9Bn4AOCr7ruWfy02F1SpHQpzTeqctLOivemkImmO6KdVpFAU77ix146FYtKZyGN9xjzE91kzLU/6Xo5zLRdq034UjurDaDB9M4zagBbN/XABxAsWz/5il+R9hL+xbHaS/YEfaJNchhA4997lIJhV34A5Wy6PnKMA+BIgrwkF+6UdTIjhj6yEPbs9DLOeP25VroamkTmE9IxrA4jRJatw3MhU3cWlT1+7pnmaccu+bVQ0QPa56xvTKItuZl11fvSTcRt+8wohDRrITiTd14gasKKVtbAj2zlHQr/mFZjCjE3MRqPV2LzyFwBCANtAxiEHttZzRZiemV1GjcZdb72EGAb+ovtt3t6eL7aqZIoDcJjRe+kwTtb6TACN508CX96GW6Yjk3nV9bW0wkS6b7jMrEUAdkvf6I/x/qbF7crCZf3Kxyx4wj9ELlPlHQhPT2+Itx7oOfTIWyokYsrjs2ox4RqJUaxL6yNWzkluSxFnMK12i3R5zs4fnGeBwSUOyqazdoGzQos9k7d21b3CNXjMmswHkfSQ="
>>>>>>> Stashed changes
  on:
    repo: netguru-code-college/vol3-green